version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=abc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    networks:
      - default
  web-1:
    image: attendant-app
    stop_signal: SIGINT
    environment:
      DB_CONN: "postgresql://postgres:postgres@db:5432/abc"
    ports:
      - "8000:8000"
    depends_on:
      - db
  web-2:
    image: attendant-app
    stop_signal: SIGINT
    environment:
      DB_CONN: "postgresql://postgres:postgres@db:5432/abc"
    ports:
      - "8001:8000"
    depends_on:
      - db
  web-3:
    image: attendant-app
    stop_signal: SIGINT
    environment:
      DB_CONN: "postgresql://postgres:postgres@db:5432/abc"
    ports:
      - "8002:8000"
    depends_on:
      - db
  api-gateway:
    image: apigateway-app
    stop_signal: SIGINT
    environment:
      ENDPOINTS: "http://web-1:8000,http://web-2:8000,http://web-3:8000"
      REDIS_ENDPOINT: "redis://redis:6379/0"
    ports:
      - "7999:5000"
    depends_on:
      - web-1
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - default

